name: AndroidLint

on:
  pull_request:
    on:
      push:
        # Pattern matched against refs/tags
        tags:
          - onekey/*    # Push events to every tag including hierarchical tags like onekey/v2.0.5

jobs:
  android_lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: |
            - ~/.cache/pip
            - ~/.cache/chaquopy
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Setup cert
        run: ./.github/secrets/decrypt_keystore.sh
        env:
          IOS_CERTIFICATE_PASS: ${{ secrets.IOS_CERTIFICATE_PASS }}
          ENCRYPT_PASS: ${{ secrets.ENCRYPT_PASS }}
      - name: build release
        run: |
          yes | /usr/local/lib/android/sdk/tools/bin/sdkmanager "platforms;android-29"
          echo 'sdk.dir=/usr/local/lib/android/sdk'>local.properties
          ./gradlew app:assembleMainNetRelease
        working-directory: android
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: push to server
        run: |
            export MAINNET_APK_PATH=`ls android/app/build/outputs/apk/MainNet/Release/*.apk`
            scp "$MAINNET_APK_PATH" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/output/
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /output && ./push_release.sh $MAINNET_APK_PATH >android_release.log" 
